services:
  bigtop-hostname0:
    hostname: bigtop-hostname0.demo.local
    command: /sbin/init
    container_name: bigtop-hostname0
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    ports:
      - "8080:8080" # Ambari Server UI
      - "3000:3000" # Ambari Metrics Grafana UI
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari

  bigtop-hostname1:
    hostname: bigtop-hostname1.demo.local
    command: /sbin/init
    container_name: bigtop-hostname1
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari

  bigtop-hostname2:
    hostname: bigtop-hostname2.demo.local
    command: /sbin/init
    container_name: bigtop-hostname2
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari

  bigtop-hostname3:
    hostname: bigtop-hostname3.demo.local
    command: /sbin/init
    container_name: bigtop-hostname3
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari